# Generated by Django 5.0.3 on 2024-05-11 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="choice",
            new_name="name",
        ),
    ]
