# Generated by Django 5.0.3 on 2024-05-14 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_choice_choice_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="votes",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="voters",
        ),
        migrations.AddField(
            model_name="choice",
            name="voters",
            field=models.ManyToManyField(
                blank=True, related_name="voters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
